### ISSUE TITLE
Bug with no-intercept model

### ISSUE THREAD

**Issue by jcarlen** [statnet/latentnet#4]
Hi Pavel (et al),

I'm getting an error when removing the intercept from a model. Below is a small, reproducible example. (Package version 2.10.0.1545). 

```
library(latentnet)
data(florentine)

# Load a sample directed network
data("faux.desert.high")

test.nointercept = ergmm(faux.desert.high ~ euclidean(d=2) + rsender + rreceiver - 1)
test.nointercept = ergmm(faux.desert.high ~ euclidean(d=2) + rsender + rreceiver - 1,
   prior = ergmm.prior(adjust.beta.var = FALSE))
````
Note the model terms besides -1 aren't necessary to reproduce, but I included them since they were part of my motivating example. Either representation of the no-intercept model (-1 or +0) returns the error "Error in model[["X"]][[i]] : subscript out of bounds". I traced it back to the immediate cause, but I'm not sure how to fix it without breaking something else.

With the default `adjust.beta.var = TRUE` the error come from the line of `ergmm.get.model`:
````
  if (prior[["adjust.beta.var"]]) 
    model[["prior"]][["beta.var"]] <- model[["prior"]][["beta.var"]]/sapply(1:model[["p"]], 
      function(i) mean((model[["X"]][[i]][observed.dyads(model[["Yg"]])])^2))
````

With `adjust.beta.var = FALSE` the error come from the line of `get.beta.eff` called by `ergmm.get.model`. (Note model[["p"]] is 0 in this case) :

````
  out <- list(sender = if (model[["sender"]]) t(sapply(1:model[["p"]], 
    function(k) apply(model[["X"]][[k]], 1, mean))), receiver = if (model[["receiver"]]) t(sapply(1:model[["p"]], 
    function(k) apply(model[["X"]][[k]], 2, mean))), sociality = if (model[["sociality"]]) t(sapply(1:model[["p"]], 
    function(k) apply(model[["X"]][[k]], 1, mean) + apply(model[["X"]][[k]], 
      2, mean))))
````

In contrast, this model is fine:
`test.intercept = ergmm(faux.desert.high ~ euclidean(d=2) + rsender + rreceiver)`

**Comment by krivit** [comment]
Thanks for the report! It looks like the problem is that the code can't handle a model with no fixed effects at all. (Whether it's a good idea to fit a model with no intercept in this case is a separate question.)

I'll see about fixing it.
