### ISSUE TITLE
ergmm gives error: Input vector wrong length

### ISSUE THREAD

**Issue by leavanh** [statnet/latentnet#7]
To reproduce:
s <- c(FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE)
sociomatrix <- matrix(data = s, nrow = 10, ncol = 10)
network <- as.network(x = sociomatrix, 
                        directed = FALSE, 
                        loops = FALSE, 
                        vertex.attr = c(1:10),
                        matrix.type = "adjacency")

Try to fit 
ergmm(network ~ euclidean(6), tofit = "mle")

**Comment by krivit** [comment]
@leavanh , I haven't had a chance to look at this ticket yet, but it looks like there isn't enough information in the network for the latent space dimension; but the error should definitely be less cryptic.
